-- =====================================================================
-- ZENDA — Base de datos completa (esquema oficial MR_ZENDA + seed local)
-- =====================================================================
-- AGUAS: este script BORRA las tablas viejas del esquema anterior
-- (usuarios antigua + instructor_fichas) y crea TODO desde cero.
-- Se aplica con:  psql -U postgres -h localhost -d zenda -f zenda_bd.sql
--
-- Nota de desviación (única con el esquema oficial):
--   A la tabla usuarios se le AGREGARON las columnas tipo_documento y
--   numero_documento, porque los formularios de la app piden el documento
--   de identidad y el esquema oficial no lo contemplaba.
--
-- Credenciales de seed:
--   admin@zenda.com / Admin123!        (ADMINISTRADOR)
--   *.zenda.com      / Prueba123!      (instructores, coordinadores, aprendices)
-- =====================================================================

-- ---------------------------------------------------------------
-- 0. Bajamos lo que había del esquema anterior
-- ---------------------------------------------------------------
DROP TABLE IF EXISTS instructor_fichas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- ---------------------------------------------------------------
-- 1. Esquema oficial — MR_ZENDA.sql (tal cual lo entregó el equipo)
-- ---------------------------------------------------------------
CREATE TYPE "tipo_rol" AS ENUM (
  'APRENDIZ',
  'INSTRUCTOR',
  'COORDINADOR',
  'ADMINISTRADOR'
);

CREATE TABLE "programas" (
  "programa_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_programa" int UNIQUE NOT NULL,
  "nombre_programa" varchar(220) NOT NULL
);

CREATE TABLE "usuarios" (
  "usuario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" tipo_rol NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'Activo',
  "fecha_creacion" timestamp NOT NULL,
  "fecha_actualizacion" timestamp NOT NULL
);

CREATE TABLE "fichas" (
  "ficha_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "programa_id" int NOT NULL,
  "numero_ficha" int UNIQUE NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "jornada" varchar(20)
);

CREATE TABLE "instructor_ficha" (
  "instructor_ficha_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "instructor_id" int NOT NULL,
  "ficha_id" int NOT NULL
);

CREATE TABLE "grupos" (
  "grupo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_id" int NOT NULL,
  "lider_id" int NOT NULL,
  "nombre_grupo" varchar(50) NOT NULL,
  "codigo_grupo" varchar(30) UNIQUE NOT NULL,
  "estado_grupo" varchar(20) NOT NULL DEFAULT 'Activo',
  "fecha_creacion" timestamp NOT NULL
);

CREATE TABLE "integrantes_grupo" (
  "integrante_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "rol_scrum" varchar(30) NOT NULL,
  "estado_integrante" varchar(20) NOT NULL DEFAULT 'Activo',
  "fecha_ingreso" timestamp NOT NULL,
  "fecha_salida" timestamp
);

CREATE TABLE "proyectos" (
  "proyecto_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_id" int UNIQUE NOT NULL,
  "nombre_proyecto" varchar(150) NOT NULL,
  "descripcion" text NOT NULL,
  "problema" text NOT NULL,
  "objetivo" text NOT NULL,
  "alcance" text NOT NULL,
  "tecnologias" text,
  "fecha_inicio" date NOT NULL,
  "fecha_fin_estimada" date NOT NULL,
  "estado_proyecto" varchar(30) NOT NULL DEFAULT 'Activo'
);

CREATE TABLE "fases" (
  "fase_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" int NOT NULL,
  "numero_fase" int NOT NULL,
  "nombre_fase" varchar(100) NOT NULL,
  "estado_fase" varchar(30) NOT NULL DEFAULT 'Pendiente'
);

CREATE TABLE "carpetas" (
  "carpeta_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fase_id" int NOT NULL,
  "nombre_carpeta" varchar(150) NOT NULL,
  "fecha_creacion" timestamp NOT NULL
);

CREATE TABLE "evidencias" (
  "evidencia_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "carpeta_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "nombre_evidencia" varchar(200) NOT NULL,
  "tipo_evidencia" varchar(20) NOT NULL,
  "ubicacion" text NOT NULL,
  "fecha_subida" timestamp NOT NULL
);

CREATE TABLE "evaluaciones" (
  "evaluacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evidencia_id" int NOT NULL,
  "instructor_id" int NOT NULL,
  "resultado" varchar(20) NOT NULL,
  "fecha_evaluacion" timestamp NOT NULL
);

CREATE TABLE "observaciones" (
  "observacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evidencia_id" int,
  "proyecto_id" int NOT NULL,
  "instructor_id" int NOT NULL,
  "titulo" varchar(150) NOT NULL,
  "descripcion" text NOT NULL,
  "fecha_observacion" timestamp NOT NULL
);

CREATE TABLE "tareas" (
  "tarea_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" int NOT NULL,
  "responsable_id" int NOT NULL,
  "titulo" varchar(150) NOT NULL,
  "descripcion" text,
  "prioridad" varchar(20) NOT NULL DEFAULT 'Media',
  "estado" varchar(20) NOT NULL DEFAULT 'Pendiente',
  "fecha_inicio" date,
  "fecha_limite" date,
  "fecha_finalizacion" date
);

CREATE TABLE "eventos" (
  "evento_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creador_id" int NOT NULL,
  "proyecto_id" int,
  "ficha_id" int,
  "titulo" varchar(150) NOT NULL,
  "descripcion" text,
  "fecha_inicio" timestamp NOT NULL,
  "fecha_fin" timestamp
);

CREATE TABLE "anuncios" (
  "anuncio_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creador_id" int NOT NULL,
  "titulo" varchar(200) NOT NULL,
  "descripcion" text NOT NULL,
  "fecha_publicacion" timestamp NOT NULL
);

CREATE TABLE "anuncio_ficha" (
  "anuncio_id" int NOT NULL,
  "ficha_id" int NOT NULL,
  PRIMARY KEY ("anuncio_id", "ficha_id")
);

CREATE TABLE "anuncio_grupo" (
  "anuncio_id" int NOT NULL,
  "grupo_id" int NOT NULL,
  PRIMARY KEY ("anuncio_id", "grupo_id")
);

CREATE UNIQUE INDEX ON "instructor_ficha" ("instructor_id", "ficha_id");

CREATE UNIQUE INDEX ON "integrantes_grupo" ("grupo_id", "usuario_id");

CREATE UNIQUE INDEX ON "fases" ("proyecto_id", "numero_fase");

ALTER TABLE "fichas" ADD FOREIGN KEY ("programa_id") REFERENCES "programas" ("programa_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "instructor_ficha" ADD FOREIGN KEY ("instructor_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "instructor_ficha" ADD FOREIGN KEY ("ficha_id") REFERENCES "fichas" ("ficha_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupos" ADD FOREIGN KEY ("ficha_id") REFERENCES "fichas" ("ficha_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupos" ADD FOREIGN KEY ("lider_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "integrantes_grupo" ADD FOREIGN KEY ("grupo_id") REFERENCES "grupos" ("grupo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "integrantes_grupo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proyectos" ADD FOREIGN KEY ("grupo_id") REFERENCES "grupos" ("grupo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fases" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carpetas" ADD FOREIGN KEY ("fase_id") REFERENCES "fases" ("fase_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evidencias" ADD FOREIGN KEY ("carpeta_id") REFERENCES "carpetas" ("carpeta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evidencias" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluaciones" ADD FOREIGN KEY ("evidencia_id") REFERENCES "evidencias" ("evidencia_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluaciones" ADD FOREIGN KEY ("instructor_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "observaciones" ADD FOREIGN KEY ("evidencia_id") REFERENCES "evidencias" ("evidencia_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "observaciones" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "observaciones" ADD FOREIGN KEY ("instructor_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tareas" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tareas" ADD FOREIGN KEY ("responsable_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eventos" ADD FOREIGN KEY ("creador_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eventos" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eventos" ADD FOREIGN KEY ("ficha_id") REFERENCES "fichas" ("ficha_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anuncios" ADD FOREIGN KEY ("creador_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anuncio_ficha" ADD FOREIGN KEY ("anuncio_id") REFERENCES "anuncios" ("anuncio_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anuncio_ficha" ADD FOREIGN KEY ("ficha_id") REFERENCES "fichas" ("ficha_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anuncio_grupo" ADD FOREIGN KEY ("anuncio_id") REFERENCES "anuncios" ("anuncio_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anuncio_grupo" ADD FOREIGN KEY ("grupo_id") REFERENCES "grupos" ("grupo_id") DEFERRABLE INITIALLY IMMEDIATE;

-- ---------------------------------------------------------------
-- 2. Extensión (única desviación): documento de identidad
-- ---------------------------------------------------------------
ALTER TABLE "usuarios"
  ADD COLUMN "tipo_documento" varchar(10),
  ADD COLUMN "numero_documento" varchar(30);

-- =====================================================================
-- 3. SEED local (datos de prueba)
-- =====================================================================

-- Programas
INSERT INTO programas (codigo_programa, nombre_programa) VALUES
  (2338, 'Análisis y Desarrollo de Software'),
  (2288, 'Desarrollo de Videojuegos'),
  (2515, 'Mantenimiento de Software');

-- Fichas
INSERT INTO fichas (programa_id, numero_ficha, fecha_inicio, fecha_fin, jornada)
SELECT p.programa_id, v.numero, v.di::date, v.df::date, v.jornada
FROM programas p
JOIN (VALUES
  (2338, 2724285, '2024-02-05', '2026-05-29', 'Diurna'),
  (2338, 2724310, '2024-02-05', '2026-05-29', 'Diurna'),
  (2288, 2724290, '2024-07-15', '2026-10-30', 'Tarde'),
  (2515, 2724315, '2024-02-12', '2026-05-30', 'Diurna')
) AS v(cod, numero, di, df, jornada) ON v.cod = p.codigo_programa;

-- Usuarios
INSERT INTO usuarios (rol, nombre, apellido, correo, contrasena, estado, fecha_creacion, fecha_actualizacion, tipo_documento, numero_documento) VALUES
  ('ADMINISTRADOR', 'Admin', 'Zenda', 'admin@zenda.com', '$2a$10$KTij7coUz/NPRQwD5KUovO3GebSej8gXw3IJdzIq.UlSD4nYRqmuS', 'Activo', now(), now(), 'CC', '1000000001'),
  ('INSTRUCTOR',    'Felipe', 'Castro',   'felipe@zenda.com', '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000002'),
  ('INSTRUCTOR',    'Rosa',   'Silva',    'rosa@zenda.com',   '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000003'),
  ('INSTRUCTOR',    'Pedro',  'Contreras','pedro@zenda.com',  '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000004'),
  ('COORDINADOR',   'Maria',  'Torres',   'maria@zenda.com',  '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000005'),
  ('COORDINADOR',   'Julian', 'Diaz',     'julian@zenda.com', '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000006'),
  ('APRENDIZ',      'Carlos', 'Mendez',   'carlos@zenda.com', '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000007'),
  ('APRENDIZ',      'Juan',   'Ramirez',  'juan@zenda.com',   '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000008'),
  ('APRENDIZ',      'Marta',  'Gomez',    'marta@zenda.com',  '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'TI', '1000000009'),
  ('APRENDIZ',      'Laura',  'Perez',    'laura@zenda.com',  '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000010'),
  ('APRENDIZ',      'Luis',   'Rojas',    'luis@zenda.com',   '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000011'),
  ('APRENDIZ',      'Ana',    'Lopez',    'ana@zenda.com',    '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000012'),
  ('APRENDIZ',      'Sofia',  'Herrera',  'sofia@zenda.com',  '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000013'),
  ('APRENDIZ',      'Camila', 'Ruiz',     'camila@zenda.com', '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'TI', '1000000014'),
  ('APRENDIZ',      'Jose',   'Sanchez',  'jose@zenda.com',   '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000015'),
  ('APRENDIZ',      'Diego',  'Cardenas','diego@zenda.com',  '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000016'),
  ('APRENDIZ',      'Valentina','Cruz',  'valentina@zenda.com','$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000017'),
  ('APRENDIZ',      'Sara',   'Vega',     'sara@zenda.com',   '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000018');

-- Instructor ↔ fichas
INSERT INTO instructor_ficha (instructor_id, ficha_id)
SELECT u.usuario_id, f.ficha_id
FROM usuarios u, fichas f
WHERE u.correo = 'felipe@zenda.com' AND f.numero_ficha IN (2724285, 2724310);

INSERT INTO instructor_ficha (instructor_id, ficha_id)
SELECT u.usuario_id, f.ficha_id
FROM usuarios u, fichas f
WHERE u.correo = 'rosa@zenda.com'  AND f.numero_ficha IN (2724310, 2724315);

INSERT INTO instructor_ficha (instructor_id, ficha_id)
SELECT u.usuario_id, f.ficha_id
FROM usuarios u, fichas f
WHERE u.correo = 'pedro@zenda.com' AND f.numero_ficha IN (2724290, 2724315);

-- Grupos "General" (uno por ficha, lider = un aprendiz de esa ficha)
INSERT INTO grupos (ficha_id, lider_id, nombre_grupo, codigo_grupo, estado_grupo, fecha_creacion)
SELECT f.ficha_id,
       (SELECT u.usuario_id FROM usuarios u WHERE u.correo = g.leader),
       'General', g.codigo, 'Activo', now()
FROM fichas f
JOIN (VALUES
  (2724285, 'GEN-2724285', 'carlos@zenda.com'),
  (2724310, 'GEN-2724310', 'laura@zenda.com'),
  (2724290, 'GEN-2724290', 'sofia@zenda.com'),
  (2724315, 'GEN-2724315', 'diego@zenda.com')
) AS g(numero, codigo, leader) ON g.numero = f.numero_ficha;

-- Aprendices dentro de su ficha
INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Integrante', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724285' AND f.numero_ficha = 2724285
  AND u.correo IN ('carlos@zenda.com', 'juan@zenda.com', 'marta@zenda.com');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Integrante', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724310' AND f.numero_ficha = 2724310
  AND u.correo IN ('laura@zenda.com', 'luis@zenda.com', 'ana@zenda.com');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Integrante', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724290' AND f.numero_ficha = 2724290
  AND u.correo IN ('sofia@zenda.com', 'camila@zenda.com', 'jose@zenda.com');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Integrante', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724315' AND f.numero_ficha = 2724315
  AND u.correo IN ('diego@zenda.com', 'valentina@zenda.com', 'sara@zenda.com');