-- =====================================================================
-- ZENDA — Base de datos completa (esquema oficial MR_ZENDA + seed local)
-- =====================================================================
-- AGUAS: este script BORRA las tablas viejas del esquema anterior
-- (usuarios antigua + instructor_fichas) y crea TODO desde cero.
-- Se aplica con:  psql -U postgres -h localhost -d zenda -f zenda_bd.sql
--
-- Nota de desviación (única con el esquema oficial):
--   A la tabla usuarios se le AGREGARON las columnas tipo_documento y
--   numero_documento, porque los formularios de la app piden el documento
--   de identidad y el esquema oficial no lo contemplaba.
--
-- Credenciales de seed:
--   admin@zenda.com / Admin123!        (ADMINISTRADOR)
--   *.zenda.com      / Prueba123!      (instructores, coordinadores, aprendices)
-- =====================================================================

-- ---------------------------------------------------------------
-- 0. Bajamos lo que había del esquema anterior
-- ---------------------------------------------------------------
DROP TABLE IF EXISTS tareas CASCADE;
DROP TABLE IF EXISTS observaciones CASCADE;
DROP TABLE IF EXISTS evaluaciones CASCADE;
DROP TABLE IF EXISTS evidencias CASCADE;
DROP TABLE IF EXISTS carpetas CASCADE;
DROP TABLE IF EXISTS fases CASCADE;
DROP TABLE IF EXISTS proyectos CASCADE;
DROP TABLE IF EXISTS integrantes_grupo CASCADE;
DROP TABLE IF EXISTS grupos CASCADE;
DROP TABLE IF EXISTS instructor_ficha CASCADE;
DROP TABLE IF EXISTS fichas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS programas CASCADE;
DROP TYPE IF EXISTS "tipo_rol" CASCADE;

-- ---------------------------------------------------------------
-- 1. Esquema oficial — MR_ZENDA.sql (unificado con FK e Índices)
-- ---------------------------------------------------------------
CREATE TYPE "tipo_rol" AS ENUM (
  'APRENDIZ',
  'INSTRUCTOR',
  'COORDINADOR',
  'ADMINISTRADOR'
);

CREATE TABLE "programas" (
  "programa_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_programa" int UNIQUE NOT NULL,
  "nombre_programa" varchar(220) NOT NULL
);

CREATE TABLE "usuarios" (
  "usuario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" tipo_rol NOT NULL,
  "sub_rol_intencion" varchar(20),
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "tipo_documento" varchar(10) DEFAULT 'CC',
  "numero_documento" varchar(30),
  "estado" varchar(20) NOT NULL DEFAULT 'Activo',
  "fecha_creacion" timestamp NOT NULL DEFAULT now(),
  "fecha_actualizacion" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "fichas" (
  "ficha_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "programa_id" int NOT NULL REFERENCES "programas" ("programa_id") DEFERRABLE INITIALLY IMMEDIATE,
  "numero_ficha" int UNIQUE NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "jornada" varchar(20)
);

CREATE TABLE "instructor_ficha" (
  "instructor_ficha_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "instructor_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "ficha_id" int NOT NULL REFERENCES "fichas" ("ficha_id") DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT "unq_instructor_ficha" UNIQUE ("instructor_id", "ficha_id")
);

CREATE TABLE "grupos" (
  "grupo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_id" int NOT NULL REFERENCES "fichas" ("ficha_id") DEFERRABLE INITIALLY IMMEDIATE,
  "lider_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "nombre_grupo" varchar(50) NOT NULL,
  "codigo_grupo" varchar(30) UNIQUE NOT NULL,
  "estado_grupo" varchar(20) NOT NULL DEFAULT 'Activo',
  "fecha_creacion" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "integrantes_grupo" (
  "integrante_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_id" int NOT NULL REFERENCES "grupos" ("grupo_id") DEFERRABLE INITIALLY IMMEDIATE,
  "usuario_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "rol_scrum" varchar(30) NOT NULL,
  "estado_integrante" varchar(20) NOT NULL DEFAULT 'Activo',
  "fecha_ingreso" timestamp NOT NULL DEFAULT now(),
  "fecha_salida" timestamp,
  CONSTRAINT "unq_integrantes_grupo" UNIQUE ("grupo_id", "usuario_id")
);

CREATE TABLE "proyectos" (
  "proyecto_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_id" int UNIQUE NOT NULL REFERENCES "grupos" ("grupo_id") DEFERRABLE INITIALLY IMMEDIATE,
  "nombre_proyecto" varchar(150) NOT NULL,
  "descripcion" VARCHAR(500) NOT NULL,
  "problema" VARCHAR(500) NOT NULL,
  "objetivo" VARCHAR(500) NOT NULL,
  "alcance" VARCHAR(500) NOT NULL,
  "tecnologias" VARCHAR(500),
  "fecha_inicio" date NOT NULL,
  "fecha_fin_estimada" date NOT NULL,
  "estado_proyecto" varchar(30) NOT NULL DEFAULT 'Activo'
);

CREATE TABLE "fases" (
  "fase_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" int NOT NULL REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE,
  "numero_fase" int NOT NULL,
  "nombre_fase" varchar(100) NOT NULL,
  "estado_fase" varchar(30) NOT NULL DEFAULT 'Pendiente',
  CONSTRAINT "unq_fases_proyecto" UNIQUE ("proyecto_id", "numero_fase")
);

CREATE TABLE "carpetas" (
  "carpeta_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fase_id" int NOT NULL REFERENCES "fases" ("fase_id") DEFERRABLE INITIALLY IMMEDIATE,
  "nombre_carpeta" varchar(150) NOT NULL,
  "fecha_creacion" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "evidencias" (
  "evidencia_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "carpeta_id" int NOT NULL REFERENCES "carpetas" ("carpeta_id") DEFERRABLE INITIALLY IMMEDIATE,
  "usuario_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "nombre_evidencia" varchar(200) NOT NULL,
  "tipo_evidencia" varchar(20) NOT NULL,
  "ubicacion" text NOT NULL,
  "fecha_subida" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "evaluaciones" (
  "evaluacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evidencia_id" int NOT NULL REFERENCES "evidencias" ("evidencia_id") DEFERRABLE INITIALLY IMMEDIATE,
  "instructor_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "resultado" varchar(20) NOT NULL,
  "fecha_evaluacion" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "observaciones" (
  "observacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evidencia_id" int REFERENCES "evidencias" ("evidencia_id") DEFERRABLE INITIALLY IMMEDIATE,
  "proyecto_id" int NOT NULL REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE,
  "instructor_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "titulo" varchar(150) NOT NULL,
  "descripcion" VARCHAR(500) NOT NULL,
  "fecha_observacion" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "tareas" (
  "tarea_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" int NOT NULL REFERENCES "proyectos" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE,
  "responsable_id" int NOT NULL REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE,
  "titulo" varchar(150) NOT NULL,
  "descripcion" VARCHAR(500),
  "prioridad" varchar(20) NOT NULL DEFAULT 'Media' CONSTRAINT "chk_tareas_prioridad" CHECK (prioridad IN ('Alta', 'Media', 'Baja')),
  "estado" varchar(20) NOT NULL DEFAULT 'Pendiente' CONSTRAINT "chk_tareas_estado" CHECK (estado IN ('Pendiente', 'En proceso', 'Finalizada', 'Confirmada', 'Incompleta')),
  "fecha_inicio" date,
  "fecha_limite" date,
  "fecha_finalizacion" date
);

-- =====================================================================
-- 3. SEED local (datos de prueba)
-- =====================================================================

-- Programas
INSERT INTO programas (codigo_programa, nombre_programa) VALUES
  (2338, 'Análisis y Desarrollo de Software'),
  (2288, 'Desarrollo de Videojuegos'),
  (2515, 'Mantenimiento de Software');

-- Fichas
INSERT INTO fichas (programa_id, numero_ficha, fecha_inicio, fecha_fin, jornada)
SELECT p.programa_id, v.numero, v.di::date, v.df::date, v.jornada
FROM programas p
JOIN (VALUES
  (2338, 2724285, '2024-02-05', '2026-05-29', 'Diurna'),
  (2338, 2724310, '2024-02-05', '2026-05-29', 'Diurna'),
  (2288, 2724290, '2024-07-15', '2026-10-30', 'Tarde'),
  (2515, 2724315, '2024-02-12', '2026-05-30', 'Diurna')
) AS v(cod, numero, di, df, jornada) ON v.cod = p.codigo_programa;

-- Usuarios
INSERT INTO usuarios (rol, sub_rol_intencion, nombre, apellido, correo, contrasena, estado, fecha_creacion, fecha_actualizacion, tipo_documento, numero_documento) VALUES
  ('ADMINISTRADOR', NULL,           'Admin',     'Zenda',     'admin@zenda.com',     '$2a$10$KTij7coUz/NPRQwD5KUovO3GebSej8gXw3IJdzIq.UlSD4nYRqmuS', 'Activo', now(), now(), 'CC', '1000000001'),
  ('INSTRUCTOR',    NULL,           'Felipe',    'Castro',    'felipe@zenda.com',    '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000002'),
  ('INSTRUCTOR',    NULL,           'Rosa',      'Silva',     'rosa@zenda.com',      '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000003'),
  ('INSTRUCTOR',    NULL,           'Pedro',     'Contreras', 'pedro@zenda.com',     '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000004'),
  ('COORDINADOR',   NULL,           'Maria',     'Torres',    'maria@zenda.com',     '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000005'),
  ('COORDINADOR',   NULL,           'Julian',    'Diaz',      'julian@zenda.com',    '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000006'),
  ('APRENDIZ',      'Scrum Master', 'Carlos',    'Mendez',    'carlos@zenda.com',    '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000007'),
  ('APRENDIZ',      'Developer',    'Juan',      'Ramirez',   'juan@zenda.com',      '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000008'),
  ('APRENDIZ',      'Developer',    'Marta',     'Gomez',     'marta@zenda.com',     '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'TI', '1000000009'),
  ('APRENDIZ',      'Scrum Master', 'Laura',     'Perez',     'laura@zenda.com',     '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000010'),
  ('APRENDIZ',      'Developer',    'Luis',      'Rojas',     'luis@zenda.com',      '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000011'),
  ('APRENDIZ',      'Developer',    'Ana',       'Lopez',     'ana@zenda.com',       '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000012'),
  ('APRENDIZ',      'Scrum Master', 'Sofia',     'Herrera',   'sofia@zenda.com',     '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000013'),
  ('APRENDIZ',      'Developer',    'Camila',    'Ruiz',      'camila@zenda.com',    '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'TI', '1000000014'),
  ('APRENDIZ',      'Developer',    'Jose',      'Sanchez',   'jose@zenda.com',      '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000015'),
  ('APRENDIZ',      'Scrum Master', 'Diego',     'Cardenas',  'diego@zenda.com',     '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000016'),
  ('APRENDIZ',      'Developer',    'Valentina', 'Cruz',      'valentina@zenda.com', '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000017'),
  ('APRENDIZ',      'Developer',    'Sara',      'Vega',      'sara@zenda.com',      '$2a$10$g5ohsmihJ4Aikk7xGQl9DOnr76qhVp3IYd4377ItCIJgw3BiaLgB6', 'Activo', now(), now(), 'CC', '1000000018');

-- Instructor ↔ fichas
INSERT INTO instructor_ficha (instructor_id, ficha_id)
SELECT u.usuario_id, f.ficha_id
FROM usuarios u, fichas f
WHERE u.correo = 'felipe@zenda.com' AND f.numero_ficha IN (2724285, 2724310);

INSERT INTO instructor_ficha (instructor_id, ficha_id)
SELECT u.usuario_id, f.ficha_id
FROM usuarios u, fichas f
WHERE u.correo = 'rosa@zenda.com'  AND f.numero_ficha IN (2724310, 2724315);

INSERT INTO instructor_ficha (instructor_id, ficha_id)
SELECT u.usuario_id, f.ficha_id
FROM usuarios u, fichas f
WHERE u.correo = 'pedro@zenda.com' AND f.numero_ficha IN (2724290, 2724315);

-- Grupos "General" (uno por ficha, lider = un aprendiz de esa ficha)
INSERT INTO grupos (ficha_id, lider_id, nombre_grupo, codigo_grupo, estado_grupo, fecha_creacion)
SELECT f.ficha_id,
       (SELECT u.usuario_id FROM usuarios u WHERE u.correo = g.leader),
       'General', g.codigo, 'Activo', now()
FROM fichas f
JOIN (VALUES
  (2724285, 'GEN-2724285', 'carlos@zenda.com'),
  (2724310, 'GEN-2724310', 'laura@zenda.com'),
  (2724290, 'GEN-2724290', 'sofia@zenda.com'),
  (2724315, 'GEN-2724315', 'diego@zenda.com')
) AS g(numero, codigo, leader) ON g.numero = f.numero_ficha;

-- Aprendices dentro de su ficha
INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Scrum Master', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724285' AND f.numero_ficha = 2724285 AND u.correo = 'carlos@zenda.com';

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Developer', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724285' AND f.numero_ficha = 2724285 AND u.correo IN ('juan@zenda.com', 'marta@zenda.com');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Scrum Master', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724310' AND f.numero_ficha = 2724310 AND u.correo = 'laura@zenda.com';

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Developer', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724310' AND f.numero_ficha = 2724310 AND u.correo IN ('luis@zenda.com', 'ana@zenda.com');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Scrum Master', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724290' AND f.numero_ficha = 2724290 AND u.correo = 'sofia@zenda.com';

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Developer', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724290' AND f.numero_ficha = 2724290 AND u.correo IN ('camila@zenda.com', 'jose@zenda.com');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Scrum Master', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724315' AND f.numero_ficha = 2724315 AND u.correo = 'diego@zenda.com';

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante, fecha_ingreso)
SELECT gr.grupo_id, u.usuario_id, 'Developer', 'Activo', now()
FROM grupos gr, usuarios u, fichas f
WHERE gr.codigo_grupo = 'GEN-2724315' AND f.numero_ficha = 2724315 AND u.correo IN ('valentina@zenda.com', 'sara@zenda.com');

-- ---------------------------------------------------------------
-- DATA DE PRUEBA COMPLEMENTARIA (Proyectos, Fases, Evidencias, Tareas)
-- ---------------------------------------------------------------

-- Proyecto de prueba para la ficha 2724285
INSERT INTO proyectos (grupo_id, nombre_proyecto, descripcion, problema, objetivo, alcance, tecnologias, fecha_inicio, fecha_fin_estimada, estado_proyecto)
SELECT g.grupo_id,
       'ZENDA - Sistema de Gestión de Proyectos',
       'Plataforma integral para el control de evidencias académicas y seguimiento de fichas ADSO.',
       'Falta de centralización en el seguimiento de entregables entre aprendices e instructores.',
       'Digitalizar y automatizar el flujo de revisión metodológica por fases.',
       'Módulos para Administrador, Coordinador, Instructor y Aprendiz.',
       'React, Node.js, Express, PostgreSQL',
       '2024-03-01', '2026-05-15', 'Activo'
FROM grupos g WHERE g.codigo_grupo = 'GEN-2724285';

-- Fases para el proyecto
INSERT INTO fases (proyecto_id, numero_fase, nombre_fase, estado_fase)
SELECT p.proyecto_id, f.num, f.nombre, f.estado
FROM proyectos p
JOIN (VALUES
  (1, 'Fase 1: Análisis', 'Aprobada'),
  (2, 'Fase 2: Planeación', 'Aprobada'),
  (3, 'Fase 3: Diseño', 'En proceso'),
  (4, 'Fase 4: Desarrollo', 'Pendiente'),
  (5, 'Fase 5: Cierre', 'Pendiente')
) AS f(num, nombre, estado) ON p.nombre_proyecto LIKE 'ZENDA%';

-- Carpetas de entrega
INSERT INTO carpetas (fase_id, nombre_carpeta, fecha_creacion)
SELECT fase_id, 'Documentación de Requisitos y Diagramas UML', now()
FROM fases WHERE numero_fase = 1;

-- Evidencias de entregas
INSERT INTO evidencias (carpeta_id, usuario_id, nombre_evidencia, tipo_evidencia, ubicacion, fecha_subida)
SELECT c.carpeta_id, u.usuario_id, 'Especificación_SRS_ZENDA.pdf', 'Documento', 'https://zenda-storage.sena.edu.co/evidencias/srs.pdf', now()
FROM carpetas c, usuarios u WHERE u.correo = 'carlos@zenda.com' LIMIT 1;

-- Evaluaciones de evidencias
INSERT INTO evaluaciones (evidencia_id, instructor_id, resultado, fecha_evaluacion)
SELECT e.evidencia_id, u.usuario_id, 'APROBADO', now()
FROM evidencias e, usuarios u WHERE u.correo = 'felipe@zenda.com' LIMIT 1;

-- Observaciones del instructor
INSERT INTO observaciones (evidencia_id, proyecto_id, instructor_id, titulo, descripcion, fecha_observacion)
SELECT e.evidencia_id, p.proyecto_id, u.usuario_id,
       'Aprobación de Arquitectura de Software',
       'El diagrama de entidades cumple con las restricciones requeridas para la cohorte ADSO.',
       now()
FROM evidencias e, proyectos p, usuarios u WHERE u.correo = 'felipe@zenda.com' LIMIT 1;

-- Tareas de la célula de proyecto
INSERT INTO tareas (proyecto_id, responsable_id, titulo, descripcion, prioridad, estado, fecha_inicio, fecha_limite)
SELECT p.proyecto_id, u.usuario_id,
       'Diseño de Interfaces en Figma',
       'Maquetación responsiva con palette de colores institucional.',
       'Alta', 'En proceso', '2024-03-10', '2026-04-01'
FROM proyectos p, usuarios u WHERE u.correo = 'juan@zenda.com' LIMIT 1;


-- =====================================================================
-- SEED AMPLIADO PARA GRÁFICAS Y MÉTRICAS (TODOS LOS RÓLES)
-- =====================================================================

-- 1. PROYECTOS ADICIONALES (Para Donut de Estados en Admin y Coordinador)
-- ---------------------------------------------------------------------
-- Proyecto 2 (Finalizado)
INSERT INTO grupos (ficha_id, lider_id, nombre_grupo, codigo_grupo, estado_grupo) VALUES
  (2, (SELECT usuario_id FROM usuarios WHERE correo = 'laura@zenda.com'), 'Célula Beta ADSO', 'PRY-2724310-01', 'Activo');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante) VALUES
  ((SELECT grupo_id FROM grupos WHERE codigo_grupo = 'PRY-2724310-01'), (SELECT usuario_id FROM usuarios WHERE correo = 'laura@zenda.com'), 'Scrum Master', 'Activo'),
  ((SELECT grupo_id FROM grupos WHERE codigo_grupo = 'PRY-2724310-01'), (SELECT usuario_id FROM usuarios WHERE correo = 'luis@zenda.com'), 'Developer', 'Activo');

INSERT INTO proyectos (grupo_id, nombre_proyecto, descripcion, problema, objetivo, alcance, tecnologias, fecha_inicio, fecha_fin_estimada, estado_proyecto) VALUES
  ((SELECT grupo_id FROM grupos WHERE codigo_grupo = 'PRY-2724310-01'), 'App Móvil Inventario SENA', 'Aplicación móvil para captura de activos en sedes', 'Pérdida de inventario en laboratorios', 'Automatizar el registro por código QR', 'Módulo Android e iOS', 'Flutter, Firebase', '2024-01-15', '2025-11-30', 'Finalizado');

-- Proyecto 3 (Pausado)
INSERT INTO grupos (ficha_id, lider_id, nombre_grupo, codigo_grupo, estado_grupo) VALUES
  (3, (SELECT usuario_id FROM usuarios WHERE correo = 'sofia@zenda.com'), 'Indie Game Studio', 'PRY-2724290-01', 'Activo');

INSERT INTO integrantes_grupo (grupo_id, usuario_id, rol_scrum, estado_integrante) VALUES
  ((SELECT grupo_id FROM grupos WHERE codigo_grupo = 'PRY-2724290-01'), (SELECT usuario_id FROM usuarios WHERE correo = 'sofia@zenda.com'), 'Scrum Master', 'Activo');

INSERT INTO proyectos (grupo_id, nombre_proyecto, descripcion, problema, objetivo, alcance, tecnologias, fecha_inicio, fecha_fin_estimada, estado_proyecto) VALUES
  ((SELECT grupo_id FROM grupos WHERE codigo_grupo = 'PRY-2724290-01'), 'Pixel Quest 2D', 'Videojuego educativo sobre historia de Colombia', 'Poca adopción pedagógica en aulas escolares', 'Enseñar historia mediante mecánicas RPG', 'Nivel 1 y 2 jugables', 'Unity, C#', '2024-07-20', '2026-08-15', 'Pausado');


-- 2. FASES Y EVIDENCIAS COMPLETA (Para Resumen de Aprendiz e Instructor)
-- ---------------------------------------------------------------------
-- Fases del Proyecto 2 (Todas aprobadas para gráfica 100%)
INSERT INTO fases (proyecto_id, numero_fase, nombre_fase, estado_fase) VALUES
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'App Móvil%'), 1, 'Fase 1: Análisis', 'Aprobada'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'App Móvil%'), 2, 'Fase 2: Planeación', 'Aprobada'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'App Móvil%'), 3, 'Fase 3: Diseño', 'Aprobada'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'App Móvil%'), 4, 'Fase 4: Desarrollo', 'Aprobada'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'App Móvil%'), 5, 'Fase 5: Cierre', 'Aprobada');

-- Fases del Proyecto 3
INSERT INTO fases (proyecto_id, numero_fase, nombre_fase, estado_fase) VALUES
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'Pixel Quest%'), 1, 'Fase 1: Análisis', 'Aprobada'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'Pixel Quest%'), 2, 'Fase 2: Planeación', 'Pendiente'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'Pixel Quest%'), 3, 'Fase 3: Diseño', 'Pendiente'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'Pixel Quest%'), 4, 'Fase 4: Desarrollo', 'Pendiente'),
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'Pixel Quest%'), 5, 'Fase 5: Cierre', 'Pendiente');

-- Carpetas y Evidencias para Instructor (Gráficas de Aprobados vs Reprobados)
INSERT INTO carpetas (fase_id, nombre_carpeta) VALUES
  ((SELECT fase_id FROM fases WHERE proyecto_id = (SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE '%ZENDA%') AND numero_fase = 2), 'Diagramas de Secuencia y Casos de Uso');

INSERT INTO evidencias (carpeta_id, usuario_id, nombre_evidencia, tipo_evidencia, ubicacion) VALUES
  ((SELECT carpeta_id FROM carpetas WHERE nombre_carpeta LIKE 'Diagramas%'), (SELECT usuario_id FROM usuarios WHERE correo = 'carlos@zenda.com'), 'Diagrama_Casos_Uso.pdf', 'Documento', 'https://zenda-storage.sena.edu.co/evidencias/casos_uso.pdf');

INSERT INTO evaluaciones (evidencia_id, instructor_id, resultado) VALUES
  ((SELECT evidencia_id FROM evidencias WHERE nombre_evidencia = 'Diagrama_Casos_Uso.pdf'), (SELECT usuario_id FROM usuarios WHERE correo = 'felipe@zenda.com'), 'REPROBADO');


-- 3. TAREAS EN DIVERSOS ESTADOS (Para Kanban y Donut de Tareas en Aprendiz)
-- ---------------------------------------------------------------------
INSERT INTO tareas (proyecto_id, responsable_id, titulo, descripcion, prioridad, estado, fecha_inicio, fecha_limite) VALUES
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE '%ZENDA%'), 
   (SELECT usuario_id FROM usuarios WHERE correo = 'carlos@zenda.com'), 
   'Modelado de Base de Datos PostgreSQL', 'Crear el script SQL con restricciones e índices', 'Alta', 'Finalizada', '2024-03-02', '2024-03-15'),

  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE '%ZENDA%'), 
   (SELECT usuario_id FROM usuarios WHERE correo = 'marta@zenda.com'), 
   'Creación de Componentes UI en React', 'Layout del Panel de Coordinador y Admin', 'Media', 'Confirmada', '2024-03-10', '2024-03-28'),

  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE '%ZENDA%'), 
   (SELECT usuario_id FROM usuarios WHERE correo = 'juan@zenda.com'), 
   'Integración de Autenticación JWT', 'Conectar el Login con el Backend en Node.js', 'Alta', 'Pendiente', '2024-04-01', '2024-04-15');


-- 4. OBSERVACIONES DE ADVERTENCIA (Para Alertas Pedagógicas de Coordinación)
-- ---------------------------------------------------------------------
INSERT INTO observaciones (proyecto_id, instructor_id, titulo, descripcion) VALUES
  ((SELECT proyecto_id FROM proyectos WHERE nombre_proyecto LIKE 'Pixel Quest%'),
   (SELECT usuario_id FROM usuarios WHERE correo = 'pedro@zenda.com'),
   'Revisión Pedagógica Pendiente',
   'El grupo registra más de 15 días sin subir evidencias en la Fase de Planeación.');